package app.dav.universalsoundboard.models

import app.dav.universalsoundboard.data.FileManager
import java.util.*


class Category(val uuid: UUID, var name: String, var icon: String){

    fun getIconImageResource() : Int{
        return FileManager.convertStringToCategoryIcon(icon)
    }

    object Icons{
        const val ADD = "\uE710"
        const val EDIT = "\uE70F"
        const val CLEAR = "\uE711"
        const val CLEAR_2 = "\uE894"
        const val SEARCH = "\uE71E"
        const val CHECK = "\uE73E"
        const val CHECK_2 = "\uE8FB"
        const val CHECK_CIRCLE_OUTLINE = "\uE73A"
        const val PERSON = "\uE77B"
        const val PEOPLE = "\uE716"
        const val PORTRAIT = "\uE8B8"
        const val PERSON_PIN_CIRCLE = "\uE7EE"
        const val MOOD = "\uE76E"
        const val SENTIMENT_SATISFIED = "\uE899"
        const val THUMB_UP = "\uE8E1"
        const val THUMB_DOWN = "\uE8E0"
        const val STAR_BORDER = "\uE734"
        const val STAR = "\uE735"
        const val PHONE = "\uE717"
        const val MAIL_OUTLINE = "\uE715"
        const val DRAFTS = "\uE8C3"
        const val ALTERNATE_EMAIL = "\uE910"
        const val PHOTO_CAMERA = "\uE722"
        const val VIDEOCAM = "\uE714"
        const val DUO = "\uE8AA"
        const val SLIDESHOW = "\uE786"
        const val MIC = "\uE720"
        const val MUSIC_NOTE = "\uE8D6"
        const val QUEUE_MUSIC = "\uE90B"
        const val VOLUME_UP = "\uE767"
        const val VOLUME_OFF = "\uE74F"
        const val PLAY_ARROW = "\uE768"
        const val PAUSE = "\uE769"
        const val SHUFFLE = "\uE8B1"
        const val BOOKMARK = "\uE718"
        const val BOOKMARK_BORDER = "\uE77A"
        const val REFRESH = "\uE72C"
        const val SYNC = "\uE895"
        const val ROTATE_LEFT = "\uE7AD"
        const val REPEAT = "\uE8EB"
        const val SHARE = "\uE72D"
        const val CHAT_BUBBLE_OUTLINE = "\uE8BD"
        const val COMMENT = "\uE90A"
        const val ANNOUNCEMENT = "\uE8F3"
        const val OUTLINED_FLAG = "\uE7C1"
        const val NOTE = "\uE77F"
        const val DESCRIPTION = "\uE7C3"
        const val BUG_REPORT = "\uE7EF"
        const val REPORT = "\uE730"
        const val VISIBILITY = "\uE890"
        const val MY_LOCATION = "\uE81D"
        const val VERTICAL_ALIGN_BOTTOM = "\uE896"
        const val HELP_OUTLINE = "\uE897"
        const val PRIORITY_HIGH = "\uE8C9"
        const val FILTER_LIST = "\uE71C"
        const val LINK = "\uE71B"
        const val ATTACH_FILE = "\uE723"
        const val VPN_KEY = "\uE8D7"
        const val SETTINGS = "\uE713"
        const val KEYBOARD = "\uE765"
        const val SMARTPHONE = "\uE8EA"
        const val SAVE = "\uE74E"
        const val DELETE = "\uE74D"
        const val LOCAL_OFFER = "\uE8EC"
        const val SCHOOL = "\uE8EF"
        const val IMPORT_CONTACTS = "\uE8F1"
        const val SHOP = "\uE719"
        const val BUILD = "\uE90F"
        const val RESTAURANT = "\uE8C6"
        const val LANGUAGE = "\uE774"
        const val PUBLIC = "\uE909"
        const val LOCATION_ON = "\uE707"
        const val NAVIGATION = "\uE8F0"
        const val HOME = "\uE80F"
        const val NATURE_PEOPLE = "\uE913"
        const val CLOUD_QUEUE = "\uE753"
    }
}